name: 'David J. M. Karlsen'
description: 'Install ephemeral helm releases which gets deleted at pipeline end'
author: 'evryfs'
branding:
  icon: download-cloud
  color: blue
inputs:
  repo:
    description: 'Helm repo'
    required: true
  chart:
    description: 'Helm chart to install'
    required: true
  helm:
    description: 'Helm command'
    default: 'helm'
    required: false
  args:
    description: 'Additional args to pass to helm'
    default: '--wait --timeout 2m'
    required: false
outputs:
  releaseName:
    description: 'Generated release name on the form ${chart}-${repo}-${GITHUB_RUN_NUMBER'

runs:
  using: 'node12'
  main: 'dist/index.js'
  post: 'dist/index.js'